#ifndef PROTOCOL_H
#define PROTOCOL_H
#include <Arduino.h>

// Connection Properties
#define PROTOCOL_BAUD_RATE 4800
#define PROTOCOL_SERIAL_CONFIG SERIAL_8N1
#define PROTOCOL_DATA_SIZE 5

#define PROTOCOL_MAX_SPEED 120
#define PROTOCOL_MIN_SPEED  0

#define PROTOCOL_MAX_GRADE 400
#define PROTOCOL_MIN_GRADE 0

// A - Input Commands
#define PROTOCOL_A_START_DISCONNECT_STOP 0xA0
#define PROTOCOL_A_START_NO_DISCONNECT_STOP 0xA1
#define PROTOCOL_A_STOP_BELT 0xA2
#define PROTOCOL_A_SET_SPEED 0xA3
#define PROTOCOL_A_SET_ELEVATION 0xA4
#define PROTOCOL_A_AUTO_STOP 0xAA
#define PROTOCOL_A_AUTO_COOL_DOWN 0xAB
#define PROTOCOL_A_TOGGLE_TRANSMIT_ACK 0xAC

// B - Input Command ACKs
#define PROTOCOL_B_START_DISCONNECT_STOP 0xB0
#define PROTOCOL_B_START_NO_DISCONNECT_STOP 0xB1
#define PROTOCOL_B_STOP_BELT 0xB2
#define PROTOCOL_B_SET_SPEED 0xB3
#define PROTOCOL_B_SET_ELEVATION 0xB4
#define PROTOCOL_B_AUTO_STOP 0xBA
#define PROTOCOL_B_AUTO_COOL_DOWN 0xBB
#define PROTOCOL_B_TOGGLE_TRANSMIT_ACK 0xBC
#define PROTOCOL_B_INPUT_DATA_OUT_OF_RANGE 0xBE
#define PROTOCOL_B_ILLEGAL_COMMAND_NOT_RECOGNIZED 0xBE

// C - Status Request
#define PROTOCOL_C_BELT_STATUS 0xC0
#define PROTOCOL_C_CURRENT_ACTUAL_SPEED 0xC1
#define PROTOCOL_C_CURRENT_ACTUAL_ELEVATION 0xC2
#define PROTOCOL_C_CURRENT_SET_SPEED 0xC3
#define PROTOCOL_C_CURRENT_SET_ELEVATION 0xC4

// D - Status Response
#define PROTOCOL_D_BELT_STATUS 0xD0
#define PROTOCOL_RES_BELT_STOPPED 0x31
#define PROTOCOL_RES_BELT_STARTED_DIS_STOP 0x32
#define PROTOCOL_RES_BELT_STARTED_NO_DIS_STOP 0x33
#define PROTOCOL_D_CURRENT_ACTUAL_SPEED 0xD1
#define PROTOCOL_D_CURRENT_ACTUAL_ELEVATION 0xD2
#define PROTOCOL_D_CURRENT_SET_SPEED 0xD3
#define PROTOCOL_D_CURRENT_SET_ELEVATION 0xD4

// Received/sent data length in bytes.
#define DATA_LEN 4

#endif // PROTOCOL_H